import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Content from "../components/Content";
import ContentBottom from "../components/ContentBottom";
import Footer from "../components/Footer";
import Intro from "../components/Intro";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Assignment - The Brink Agency - Mai Bach Pham</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro />
      <Content />
      <Banner />
      <ContentBottom />
      <Footer />
    </div>
  );
}
